### ISSUE TITLE
adonis2 returning "invalid subscript type 'closure'" when identifying variables with brackets

### ISSUE THREAD

**Issue by ktmbiome** [vegandevs/vegan#285] opened 2018-07-03 18:29 UTC
Hi,

I'm really excited about the new vegan update that was recently published! I'm trying to implement `adonis2` into a script where I compare a distance matrix with a set of variables. In doing so, I set up my formulas like this: `adonis2(funcdm ~ funcmap[, var],data=funcmap)`. However in doing so, I get an `invalid subscript type "closure"` error, which did not occur previously. 

Something that does work is: `adonis2(as.formula(paste("funcdm ~", var)), data=funcmap)`, so I can potentially modify my code to work this way.

Is my previous method deprecated?

**Comment by jarioksa** [comment] 2018-07-03 19:01
This is not deprecated on purpose, but your usage was non-canonical. The correct usages are to refer to a variable name (`var`) **and** `data`, or to refer to a column in a matrix or data frame **without** `data`. 

With a reproducible example, both of the following should work (and work in **vegan** 2.6-0 development version):
```r
adonis2(dune ~ Moisture, dune.env) # var name + data
adonis2(dune ~ dune.env[, "Moisture"]) # var name in a data.frame
```
We never intended your example to work (the same example, but with reproducible data):
```r
adonis(due ~ dune.env[, Moisture], data=dune.env) # expected to fail, but worked incidentally (?)
```
We never knew that this works, and therefore we had no intention to make it fail. It should not work, but we did not disable that intentionally.

**Comment by ktmbiome** [comment] 2018-07-03 19:22
Hi Jari,

My apologies for my lack of clarity and reproducible examples in my initial post. What I'm coming across is something like the second example in your list of things that work, except when I assign "Moisture" to an object called `var` first, I get the error:

```
> var <- c("Moisture")
> adonis2(dune ~ dune.env[, var])
Error in .subset(x, j) : invalid subscript type 'closure'
```

**Comment by jarioksa** [comment] 2018-07-04 08:19
This indeed is a scoping issue. The `adonis(2)` function only finds rhs terms in `data=` or directly in the formula. The following will also fail with the same error message:
```r
with(dune.env, adonis2(dune ~ Moisture))
```
It is rather easy to fix **just this** issue, but scoping is messy, and fixing **just this** issue may break something else. I may need some time to test how to do this safely.

NB., the development version of **vegan** in the github master branch (or **vegan** 2.6-0) removes the code of old `adonis`, and there `adonis()` will use new code. The fix (if any) will be made on this version, and I am not sure it cannot be directly merged to **vegan** 2.5-x releasese.

**Comment by ktmbiome** [comment] 2018-07-05 18:35
Thank you so much for the clarification about scoping. I hadn't been aware of this type of programming problem previously. I am happy to leave this as-is, as I don't want a tweak due to my small bug to break the rest of the package. I have a work-around from the "as.formula" solution in my first post, and that works for me!

Thanks again!

**Comment by psolymos** [comment] 2018-07-05 18:45
@jarioksa : using `formula <- terms(formula, data = parent.frame())` instead of `formula <- terms(formula, data = data)` in `adonis2` (and renamed `adonis` in 2.6) solves the scoping issue.

**Comment by jarioksa** [comment] 2018-07-05 20:14
@psolymos : yes, that was the same fix I tried and found to work **just in this case**. However, I am not yet sure it will work in all case where it should: will it work if you embed `adonis(2)`? Comparison to `rda.formula` and `ordiParseFormula`  hints that you either need some more tricks or you can simplify `rda.formula` and `ordiParseFormula`. The first thing I need to do is to add `adonis(2)` tests (that are now expected to fail) and see that they work in all cases where `rda` works. I have just now some other things to think about, and therefore I have not yet done this.

**Comment by jarioksa** [comment] 2018-08-08 10:17
@ktmbiome : I think I have now fixed the issues (and some other issues) in a separate branch (see https://github.com/vegandevs/vegan/tree/adonis-scope). If nothing new appears, I will merge this to the master branch within a day or two. This will then be in **vegan_2.6-0**. Merging these changes to the **2.5-3** release probably needs some hand crafting, but should not be too complicated. Please test, if possible.

**Closed** 2018-08-10 07:31 UTC
Labels: bug
