### ISSUE TITLE
`commsim` example fails to finish

### ISSUE THREAD

**Issue by gavinsimpson** [vegandevs/vegan#171] opened 2016-04-23 19:51 UTC
I'm having trouble checking vegan under `R CMD check`. It keeps getting stuck in the `commsim` example. I modified the `evalfun` in that example to report on what is was doing:

```r
evalfun <- function(meth, x, n) {
    writeLines(paste("Doing method:", meth))
    m <- nullmodel(x, meth)
    y <- simulate(m, nsim=n)
    out <- rowMeans(sapply(1:dim(y)[3], 
                           function(i) diagfun(attr(y, "data"), y[,,i])))
    z <- as.numeric(c(attr(y, "binary"), attr(y, "isSeq"),
                      attr(y, "mode") == "double"))
    names(z) <- c("binary", "isSeq", "double")
    writeLines(paste("Method:", meth, "Completed"))
    c(z, out)
}
```

Running this with

```r
a <- t(sapply(algos, evalfun, x=x, n=10))
```

Which produces:

```r
Doing method: r00
Method: r00 Completed
Doing method: c0
Method: c0 Completed
Doing method: r0
Method: r0 Completed
Doing method: r0_old
Method: r0_old Completed
Doing method: r1
Method: r1 Completed
Doing method: r2
Method: r2 Completed
Doing method: quasiswap
Method: quasiswap Completed
Doing method: swap
Method: swap Completed
Doing method: tswap
Method: tswap Completed
Doing method: curveball
Method: curveball Completed
Doing method: backtrack
Method: backtrack Completed
Doing method: r2dtable
Method: r2dtable Completed
Doing method: swap_count
Method: swap_count Completed
Doing method: quasiswap_count
Method: quasiswap_count Completed
Doing method: swsh_samp
```

and there it just hangs until I kill the R session.

This is on:

```
> sessionInfo()
R version 3.2.4 Patched (2016-03-16 r70339)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora 22 (Twenty Two)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vegan_2.4-0     lattice_0.20-33 permute_0.9-1  

loaded via a namespace (and not attached):
[1] MASS_7.3-45    compiler_3.2.4 Matrix_1.2-5   parallel_3.2.4 tools_3.2.4   
[6] mgcv_1.8-12    nlme_3.1-127   grid_3.2.4     cluster_2.0.4
```

**Comment by jarioksa** [comment] 2016-04-24 04:37
Which version of **vegan**? Release, `master` or `bind-simmat` `HEAD`? I just ran this with `master`  and it went smoothly.

**Comment by gavinsimpson** [comment] 2016-04-24 04:39
`master`, and yes it's odd as Travis ran fine too.

**Comment by jarioksa** [comment] 2016-04-24 04:47
What about `x` in `a <- t(sapply(algos, evalfun, x=x, n=10))`? It was a random matrix. Does it have any peculiarities in your case? Row sums, column sums, fill, frequencies?

**Comment by jarioksa** [comment] 2016-04-24 04:53
For instance, the following seems to hang:
```R
x <- x+1
a <- t(sapply(algos, evalfun, x=x, n=10))
```
That is, if the fill == 1, the null model just hangs. This time already in `"swap"`. I would look at the input matrix properties. If we have problems with some input matrices, we should add guards against input matrices we cannot handle in requested null models.

**Comment by psolymos** [comment] 2016-04-24 06:23
Setting the seed or a fixed matrix can prevent strange matrices. For example, this works:

```
data(dune)
x <- as.matrix(dune)
algos <- make.commsim()
a <- t(sapply(algos, evalfun, x=x, n=10))
```

**Comment by jarioksa** [comment] 2016-04-24 11:27
Setting a seed or using a fixed matrix will solve the problem in the sense that we never see the problem, but the problem still remains. The problem is that some legitimate input can hang the function, and the only way to get out is to kill R and lose a day's work. This is not acceptable.

I assume that the failure comes from compiled C code. It is clear that with fill==1 `"swap"` will go to infinite loop since the number of checkerboards == 0 and there is nothing to swap. The C code does not listen to signals and does not allow interrupt from the R session (but we must kill R). I think the minimum is that we add signal handling in C. Currently `quasiswap`, `swapcount`, `rswapcount` and `abuswap` functions have a `while` loop, and swap has a `for(;;)` loop designed to be infinite but with a `break;` to get out. There is no guarantee that the condition to exit loop ever exists, and the example @gavinsimpson gave indicates that there are cases with no exit.

The minimum is to add an option for user interruption to get out when your are stuck and hung in an interactive session. Even better is to avoid cases that cannot be handled and signal an error to the user. Therefore I would like to see the `x` @gavinsimpson used.A step between these two is to bail out if the analysis takes too long and nothing seems to happen. 

We should fix these problems before users get bitten or these get published. Articles analysing and comparing null models typically use small artificial matrices, and these are the kind of matrices where we may expect pathological cases that hung vegan.

**Comment by jarioksa** [comment] 2016-04-24 13:22
While it is true that we need to have user interrupt, this seems to be a plain bug: the `.C` interface of `quasiswap()` got new argument `*thin`, but several functions with direct `.C` call to `quasiswap` ignored this argument. I'll fix that.

**Comment by jarioksa** [comment] 2016-04-24 13:36
The bug part was fixed in f23252d1c0. I'll work with the user interrupt in another branch (that is also needed: just for sure).

**Comment by jarioksa** [comment] 2016-04-24 14:25
User interrupt was added to the C code of nullmodel in bcf6b381. This may need tuning. For instance, the `intcheck` variable may overflow to negative integer. Testing interval could also be reconsidered.

**Comment by gavinsimpson** [comment] 2016-04-24 16:10
@jarioksa For example, this one failed with the same setup as when I reported this initially (i.e. I haven't yet pulled in the `.C` call buglet and the user interrupt code.

```r
> x
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    0    0    4    3    1    1    0    0    0     2
 [2,]    0    0    5    1    0    0    2    0    0     0
 [3,]    0    0    3    0    3    0    0    0    0     0
 [4,]    4    0    0    3    3    2    0    0    0     0
 [5,]    3    3    3    0    0    0    0    4    0     3
 [6,]    0    0    2    0    3    0    0    0    0     0
 [7,]    0    4    1    0    5    0    0    0    1     3
 [8,]    0    4    0    0    0    2    0    0    0     3
 [9,]    0    0    2    0    3    2    0    0    0     0
[10,]    0    0    2    2    4    0    0    7    3     1
[11,]    0    0    3    0    6    2    0    0    0     4
[12,]    0    2    0    0    4    2    2    4    2     3
> rowSums(x)
 [1] 11  8  6 12 16  5 14  9  7 19 15 19
> colSums(x)
 [1]  7 13 25  9 32 11  4 15  6 19
```

But the problem goes away with current `master` branch for the same matrix `x` above.

**Closed** 2016-04-25 07:13 UTC
Labels: bug
