### ISSUE TITLE
envfit cause R to abort

### ISSUE THREAD

**Issue by gazzapol** [vegandevs/vegan#252] opened 2017-09-12 14:57 UTC
when using envfit function, R will abort
I am using a R version 3.4.1 on Windows 10

Any idea why?

**Comment by jarioksa** [comment] 2017-09-12 15:25
What is the version of **vegan**? Can you provide a reproducible example?

**Comment by gazzapol** [comment] 2017-09-12 15:59
it is vegan 2.4-4, but I made a mistake when setting the "environmental" variables to use in envfit; instead of reporting that the two arguments were not matching, it aborted R. 
However, now I solved the mistake and envfit works beatifully. Apologies for the "false" issue I made.

best regards
Paolo

**Comment by jarioksa** [comment] 2017-09-12 18:10
OK. That may be a mistake, but `envfit` should not abort **R** if you make a mistake: it should be an error, but not a crash. What kind of mistake was that?

**Comment by jarioksa** [comment] 2017-09-15 08:19
This may be a user error, but **vegan** should not segfault with user errors (assuming this is what was meant with "crash"). I cannot reproduce the problem and therefore I close this now as unresolved.

**Closed by jarioksa** 2017-09-15 08:19 UTC
Labels: unresolved
